In [3]:
import tensorflow as tf

In [17]:
x = tf.Variable(tf.random_normal([5,3]),name='x')
y = tf.Variable(tf.random_normal([3,5]),name='y')
mul = tf.matmul(x,y)

In [27]:
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    res = sess.run(mul)
    
    print(res)
    
    restile = tf.tile(res,[5,3])
    print(sess.run(restile))

[[-0.49353716  0.35180366  1.15098286 -0.98705339  0.0421651 ]
 [ 0.06541498  0.02790101 -0.43476263  0.99366409 -0.18053994]
 [ 0.09676086 -0.01799862  0.47986975 -1.40808737  0.63198739]
 [ 0.03180128  0.21783172 -0.57789361  1.85530424 -0.22312346]
 [-0.67924809 -0.78444982  0.78070277 -2.368644   -1.70596361]]
[[-0.49353716  0.35180366  1.15098286 -0.98705339  0.0421651  -0.49353716
   0.35180366  1.15098286 -0.98705339  0.0421651  -0.49353716  0.35180366
   1.15098286 -0.98705339  0.0421651 ]
 [ 0.06541498  0.02790101 -0.43476263  0.99366409 -0.18053994  0.06541498
   0.02790101 -0.43476263  0.99366409 -0.18053994  0.06541498  0.02790101
  -0.43476263  0.99366409 -0.18053994]
 [ 0.09676086 -0.01799862  0.47986975 -1.40808737  0.63198739  0.09676086
  -0.01799862  0.47986975 -1.40808737  0.63198739  0.09676086 -0.01799862
   0.47986975 -1.40808737  0.63198739]
 [ 0.03180128  0.21783172 -0.57789361  1.85530424 -0.22312346  0.03180128
   0.21783172 -0.57789361  1.85530424 -0.22312346

In [35]:
temp = tf.tile([1,2,3],[1])
temp2 = tf.tile([[1,2],[3,4],[5,6]],[1,2])

print(temp)
with tf.Session() as sess:
#     print(sess.run(temp))
    print(sess.run(temp2))

Tensor("Tile_25:0", shape=(3,), dtype=int32)
[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]
